server:
  port: 12190

  tomcat:
    accesslog:
      enabled: true
    uri-encoding: UTF-8

  # gzip, compression
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

#指定当前服务的名称  会注册到注册中心
spring:
  profiles: dev
  application:
    name: security-oidc-server
  main:
    allow-bean-definition-overriding: true
  jmx:
    enabled: false

  #加载静态资源路径
  resources:
    static-locations: [classpath:/static/,classpath:/public/]

  #资源路径访问方式
  mvc:
#    static-path-pattern: [/static/**,/public/**]  #所有访问需要静态资源路径/static/**,/public/**
    ignore-default-model-on-redirect: false  #设置Spring 的 redirect 后带参数 不带参数 true

  #thymeleaf
  thymeleaf:
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/

  datasource:
#    url: jdbc:mysql://192.168.100.197:3306/db_oidc?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
#    username: root_crcc
#    password: crcc_121@root
    url: jdbc:mysql://localhost:3306/db_oidc?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Dx19800602Fb
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 2

  #JPA
  data:
    jpa:
      repositories:
        enabled: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

logging:
  level:
    root=INFO:

#  指定 服务注册中心的地址
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:@eureka-port@/eureka/
#      defaultZone: http://192.168.100.199:@eureka-port@/eureka/
#      defaultZone: http://ldsc.cr121.com:@eureka-port@/eureka/

application:
  host: http://localhost:${server.port}/
#  host: http://192.168.100.199:${server.port}/
#  host: http://ldsc.cr121.com:${server.port}/