server:
  port: 12191

  tomcat:
    accesslog:
      enabled: true
    uri-encoding: UTF-8

  # gzip, compression
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  profiles: pro
  application:
    name: provider-oidc-gongchengwbs
  main:
    allow-bean-definition-overriding: true
  jmx:
    enabled: false

  #加载静态资源路径
  resources:
    static-locations: classpath:/static/

  #资源路径访问方式
  mvc:
    #    static-path-pattern: /static/**  #所有访问需要静态资源路径/static/**
    ignore-default-model-on-redirect: false  #设置Spring 的 redirect 后带参数 不带参数 true

  #thymeleaf
  thymeleaf:
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/

  datasource:
    url: jdbc:mysql://192.168.100.197:3306/db_oidc?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root_crcc
    password: crcc_121@root
#    url: jdbc:mysql://localhost:3306/db_oidc?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
#    username: root
#    password: Dx19800602Fb
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 2


  http-client:
    pool:
      #连接池的最大连接数，0代表不限；如果取0，需要考虑连接泄露导致系统崩溃的后果
      maxTotalConnect: 1000
      #每个路由的最大连接数,如果只调用一个地址,可以将其设置为最大连接数
      maxConnectPerRoute: 200
      # 指客户端和服务器建立连接的超时时间,ms , 最大约21秒,因为内部tcp在进行三次握手建立连接时,默认tcp超时时间是20秒
      connectTimeout: 10000
      # 指客户端从服务器读取数据包的间隔超时时间,不是总读取时间,也就是socket timeout,ms
      readTimeout: 5000
      # 从连接池获取连接的timeout,不宜过大,ms
      connectionRequestTimeout: 200
      # 服务器返回数据(response)的时间，超过抛出 read timeout
      socketTimeout: 5000
      # 重试次数
      retryTimes: 3
      # 连接池编码
      charset: UTF-8
      # 长连接保持时间 单位s,不宜过长
      keepAliveTime: 10
      # 配置请求目标地址长连接保持时间
      keepAliveTargetHost:
        ldsc.cr121.com: 5
        hrapitest.crcc.cn: 5
      # 设置长连接保持时间
      ValidateAfterInactivity: 10000
      async: false

logging:
  level:
    root=INFO:

#  指定 服务注册中心的地址
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
#      defaultZone: http://localhost:@eureka-port@/eureka/
#      defaultZone: http://192.168.100.199:@eureka-port@/eureka/
      defaultZone: http://ldsc.cr121.com:@eureka-port@/eureka/

application:
#  host: http://localhost:${server.port}/
#  host: http://192.168.100.199:${server.port}/
  host: http://ldsc.cr121.com:${server.port}/